# Generated by Django 2.1.7 on 2019-03-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
