# Generated by Django 2.1.7 on 2019-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
