# Generated by Django 2.1.7 on 2019-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20190321_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
