# Generated by Django 2.1.7 on 2019-03-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_brokers', '0001_initial'),
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='identifier',
            new_name='id',
        ),
        migrations.AddField(
            model_name='door',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mqtt_brokers.Broker'),
        ),
    ]
